[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd frontend && npm install",
  "cd ../backend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd ../backend && npm run build"
]

[start]
cmd = "cd backend && npm start"

[variables]
NODE_ENV = "production"
