[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install --only=production"
]

[phases.build]
cmds = []

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
